# Generated by Django 4.1.7 on 2023-02-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookISBN', models.CharField(max_length=13)),
                ('BookName', models.CharField(max_length=500)),
                ('BookDescription', models.CharField(max_length=2000)),
                ('BookPrice', models.IntegerField(default=0)),
                ('Author', models.CharField(max_length=500)),
                ('BookGenre', models.CharField(max_length=500)),
                ('BookPublisher', models.CharField(max_length=500)),
                ('YearPublished', models.DateField()),
                ('CopiesSold', models.IntegerField(default=0)),
                ('BookRating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.EmailField(blank=True, max_length=500, null=True)),
                ('HomeAddress', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
