# Generated by Django 4.1.7 on 2023-03-11 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0002_users_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='books',
            new_name='ShoppingCart',
        ),
    ]
