# Generated by Django 4.1.7 on 2023-03-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0003_rename_books_users_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ShoppingCart',
            field=models.ManyToManyField(blank=True, default=list, to='ShoppingCart.books'),
        ),
    ]
