# Generated by Django 4.1.6 on 2023-02-21 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('email', models.EmailField(default='abc123@mail.com', max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(default='default_department', max_length=100)),
                ('joining_date', models.DateField(default='timezone.now')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('employee_count', models.IntegerField(default=0)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
