# Generated by Django 4.1.6 on 2023-02-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_deparments_employees_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deparments',
            new_name='Departments',
        ),
    ]
